export default fonts = {
  nunitoBlack: 'Nunito-Black',
  nunitoBlackItalic: 'Nunito-BlackItalic',
  nunitoBold: 'Nunito-Bold',
  nunitoBoldItalic: 'Nunito-BoldItalic',
  nunitoExtraBold: 'Nunito-ExtraBold',
  nunitoExtraBoldItalic: 'Nunito-ExtraBoldItalic',
  nunitoExtraLight: 'Nunito-ExtraLight',
  nunitoExtraLightItalic: 'Nunito-ExtraLightItalic',
  nunitoItalic: 'Nunito-Italic',
  nunitoLight: 'Nunito-Light',
  nunitoLightItalic: 'Nunito-LightItalic',
  nunitoRegular: 'Nunito-Regular',
  nunitoSemiBold: 'Nunito-SemiBold',
  nunitoSemiBoldItalic: 'Nunito-SemiBoldItalic',
};
