require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MonkeyMusic' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'

  target 'MonkeyMusicTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-places'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
 
end

target 'MonkeyMusic-tvOS' do
  # Pods for MonkeyMusic-tvOS

  target 'MonkeyMusic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


